{
    "retry.api.retry_call": [
        "Callable[..., _R]",
        "Sequence[Any] | None",
        "dict[str, Any] | None",
        "type[Exception] | tuple[type[Exception], ...]",
        "int",
        "float",
        "float | None",
        "float",
        "tuple[float, float] | float",
        "Logger | None"
    ],
    "retry.api.retry": [
        "type[Exception] | tuple[type[Exception], ...]",
        "int",
        "float",
        "float | None",
        "float",
        "tuple[float, float] | float",
        "Logger | None"
    ]
}