<?xml version="1.0" encoding="UTF-8"?>
<!--Copyright 2024 The MathWorks, Inc.-->

<rsccat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" locale="ja_JP" product="parallel" xsi:noNamespaceSchemaLocation="../../resources/schema/msgcat.xsd">
  <message>
    <entry key="AttachedFilesLink">ファイル リスト</entry>
    <entry key="AttachedFilesList">並列プールの付加ファイル:</entry>
    <entry key="AttachedFilesTransferError">Failed to transfer files to the parallel pool workers.\nThis was caused by: {0}</entry>
    <entry key="AutoAttachedFiles">並列プールに自動的に追加されるファイル:\n{0}</entry>
    <entry key="CannotDisableSPMD" context="warning">並列プールでの SPMD の無効化は、このクラスター タイプではサポートされていません。'SpmdEnabled' の値を true に設定してください。</entry>
    <entry key="CannotSetAttachedFilesProperty">並列プールにファイルを付加するには、addAttachedFiles(pool, files) を使用します。ここで、files はファイル名のセル配列です。</entry>
    <entry key="DeletedObject">オブジェクトを削除しました。</entry>
    <entry key="DiaryTruncated" context="warning">ダイアリの出力が打ち切られています。</entry>
    <entry key="DisallowedParallelFeature" context="error">スレッドベースの並列プールでは、{0} の使用はサポートされていません。たとえば 'Processes' など、別の並列環境を選択してください。</entry>
    <entry key="DoneDependencyAnalysis">完了。</entry>
    <entry key="EmptyClusterValue">名前が ''Cluster'' である名前と値のペアを使用した関数 ''parcluster'' によって返された ''parallel.Cluster'' オブジェクトを指定する必要があります。</entry>
    <entry key="FailedToInitializeInteractiveSession">並列プールを起動できませんでした。</entry>
    <entry key="FailedToRestart">並列プールを再起動できませんでした。原因: {0}</entry>
    <entry key="FailedToStartSessionServices" context="error">Error starting pool services:\n{0}</entry>
    <entry key="FevalQueueManyRequests">{0,number,integer} の未処理の future があります。</entry>
    <entry key="FevalQueueOneRequest">1 つの未処理の future があります。</entry>
    <entry key="FileTransferError">ワーカーにファイルを転送中にエラーが検出されました。再試行してください。</entry>
    <entry key="FileTransferObserverError">Unexpected error in FileTransferObserver:\n{0}</entry>
    <entry key="IdleTimeoutFiniteManyMinutes">{0,number,integer} 分</entry>
    <entry key="IdleTimeoutInfinite">Inf (自動終了なし)</entry>
    <entry key="IdleTimeoutOneMinute">1 分</entry>
    <entry key="IgnoringAlreadyAttachedFiles">既に付加されているファイルは無視されています。不可されているファイルを確認するには、並列プールの ''AttachedFiles'' プロパティを参照してください。</entry>
    <entry key="InternalRuntime">内部実行時エラーが発生しました。</entry>
    <entry key="InternalRuntimeWithCause">内部実行時エラーが発生しました。\n原因: {0}。</entry>
    <entry key="InvalidDeleteSyntax">並列プールを削除する構文が無効です。代わりに delete(pool) を使用してください。</entry>
    <entry key="InvalidDependency">{0} は有効なファイルまたはディレクトリではありません。</entry>
    <entry key="InvalidIdleTimeout">IdleTimeout パラメーターは、ゼロより大きいスカラー整数でなければなりません。</entry>
    <entry key="InvalidLogicalParameter" context="error">値は logical の ''true'' または ''false'' でなければなりません。</entry>
    <entry key="InvalidSingleInput">parpool の入力が無効です。許容される引数は、プロファイル名、cluster オブジェクト、プール サイズを指定する整数です。</entry>
    <entry key="InvalidTwoInputFirstArgument">parpool の入力が無効です。最初の引数に対して許容される値は、プロファイル名または cluster オブジェクトです。</entry>
    <entry key="InvalidTwoInputSecondArgument">parpool の入力が無効です。2 番目の引数に対して許容される値は、プール サイズを指定する整数です。</entry>
    <entry key="LostAnUnknownWorker" context="error">The client lost connection to an unknown worker, potentially due to network issues or errors during the interactive communicating job.</entry>
    <entry key="LostAnUnknownWorkerWithCause" context="error">The client lost connection to an unknown worker, potentially due to network issues or errors during the interactive communicating job.\nThis was caused by {0}.</entry>
    <entry key="LostClient" context="error">The worker lost connection to the client, potentially due to network issues or errors during the interactive communicating job.</entry>
    <entry key="LostClientWithCause" context="error">The worker lost connection to the client, potentially due to network issues or errors during the interactive communicating job.\nThis was caused by {0}.</entry>
    <entry key="LostRemoteEndPoint" context="error">Lost connection to remote end point {0}, potentially due to network issues or errors during the interactive communicating job.</entry>
    <entry key="LostWorker" context="error">クライアントからワーカー {0} への接続が切断されました。対話型通信ジョブ中にネットワークの問題またはエラーが発生した可能性があります。</entry>
    <entry key="LostWorkerWithCause" context="error">The client lost connection to worker {0}, potentially due to network issues or errors during the interactive communicating job.\nThis was caused by {1}.</entry>
    <entry key="OperationTerminatedByUser">並列プールの起動中にユーザーによって処理が終了されました。プールはアクティブではありません。</entry>
    <entry key="ParpoolProgressConnectedWorkers" context="diagnostic">{1,number,integer} 個中 {0,number,integer} 個の並列プール ワーカーに接続しました。</entry>
    <entry key="ParpoolProgressReadyWorkers" context="diagnostic">{1,number,integer} 個中 {0,number,integer} 個の並列プール ワーカーの準備ができています。</entry>
    <entry key="ParpoolProgressWaitingForRunningJob" context="diagnostic">ジョブがキューに登録されました。ID {0,number,integer} の並列プール ジョブの開始を待機しています ...</entry>
    <entry key="ParpoolProgressWaitingForWorkers" context="diagnostic">ジョブが実行中です。並列プール ワーカーの接続待ちです ...</entry>
    <entry key="PerformingDependencyAnalysis">ファイルを解析して、ワーカーに転送しています... </entry>
    <entry key="PoolArrayInvalidArgument">PoolArrayManager の演算が無効です。</entry>
    <entry key="PoolDidNotBecomeIdle" context="warning">プールが {0} ミリ秒以内にアイドル状態になりませんでした。一部のプロファイリングされたコードがまだ実行中の可能性があります。</entry>
    <entry key="PoolNotRunning" context="error">並列プールは現在実行されていません。プールを起動するには、''parpool'' を使用します。</entry>
    <entry key="PoolShutDownNoProfile">並列プールをシャットダウンしています。</entry>
    <entry key="PoolShutDownWithProfile">''{0}'' プロファイルを使用する並列プールをシャットダウンしています。</entry>
    <entry key="PoolShutdown">この並列プールが終了しています。</entry>
    <entry key="PoolShutdownNotice" context="warning">オンライン ライセンスを使用する並列プールはシャットダウンされます</entry>
    <entry key="PoolTimeout">IdleTimeout に達しました。</entry>
    <entry key="ReadFromClientError">クライアントからの読み取り中に読み取りエラーが発生しました。</entry>
    <entry key="ReadFromClientErrorWithCause">クライアントからの読み取り中に読み取りエラーが発生しました。\n原因: {0}。</entry>
    <entry key="ReadFromWorkerError">ワーカー {0} からの読み取り中に読み取りエラーが発生しました。</entry>
    <entry key="ReadFromWorkerErrorWithCause">ワーカー {0} からの読み取り中に読み取りエラーが発生しました。\n原因: {1}。</entry>
    <entry key="RestartOnClusterChangeNotAllowed">この並列プールでは、RestartOnClusterChange を true に変更することは許可されません。</entry>
    <entry key="RunOnLabs">並列プールは、ワーカーからではなく、クライアント MATLAB からのみ起動できます。</entry>
    <entry key="StartupFailed">ワーカーはクライアントとの通信を確立できませんでした。</entry>
    <entry key="StartupFailedWithCause" context="error">Worker failed to establish communication with the client.\nThis was caused by: {0}.</entry>
    <entry key="TimeToTimeoutManyMinutes">{0,number,integer} 分 (残り {1,number,integer} 分)</entry>
    <entry key="TimeToTimeoutManyMinutesOneRemaining">{0,number,integer} 分 (残り 1 分未満)</entry>
    <entry key="TimeToTimeoutOneMinute">1 分 (残り 1 分未満)</entry>
    <entry key="TimeoutConnectingToProfiler" context="error">プロファイラーに {0} 秒以内に接続できませんでした</entry>
    <entry key="TimeoutProcessingProfilerEvents" context="error">保留中のプロファイリング イベントを {0} 秒以内に処理できませんでした</entry>
    <entry key="TimeoutFromPrevious">{0} 秒待機した後、並列プールからリモート実行で使用できるワーカーがありませんでした。これは、以前の SPMD ブロックまたは PARFOR ループが正しく完了せずに中断されたか、少なくとも 1 つのワーカーが PARFEVAL の実行中のためビジーである可能性があります。この問題が解決しない場合は、並列プールの再起動が必要な場合があります。</entry>
    <entry key="TimeoutSettingUpSession">並列プールの通信のセットアップ中にタイムアウトになりました。</entry>
    <entry key="TimeoutSettingUpSessionOnClient" context="error">{0,number,integer} 秒間でワーカーのアクティビティが検出されなかったため、並列プールの通信のセットアップ中にタイムアウトになりました。このタイムアウトを変更するには pctconfig("poolstarttimeout") を使用します。</entry>
    <entry key="UnableToCompleteTransfer" context="error">Unable to complete transfer for local file(s) {0}.\nRemote error message is:{1}.</entry>
    <entry key="UnableToCompleteUpdate" context="warning">ローカル ファイル {0} の更新を完了できません。\nリモート エラー メッセージ:{1}</entry>
    <entry key="UnableToUpdateWorkerFiles" context="warning">ワーカー ファイルを更新できませんでした。\n原因: {0}</entry>
    <entry key="UnexpectedParforFailure">PARFOR の実行中に予期しないエラーが発生しました: {0}</entry>
    <entry key="UnknownError" context="error">原因不明のエラー。</entry>
    <entry key="UnsupportedFeature" context="error">構文はスレッドベースのプールではサポートされていません。</entry>
    <entry key="WorkerAborted">ワーカーが応答を停止しています。parpool を使用して、並列プールを削除して再起動します。</entry>
    <entry key="WorkerIdentifier" context="parameter">ワーカー {0,number,integer}</entry>
    <entry key="WorkerIdentifierUnknown" context="parameter">不明なワーカー</entry>
    <entry key="WorkerIndexFull" context="parameter">{0,number,integer} (タスク {1,number,integer}; ホスト: {2})</entry>
    <entry key="WriteToClientError">クライアントへの送信中に書き込みエラーが発生しました。</entry>
    <entry key="WriteToClientErrorWithCause">クライアントへの送信中に書き込みエラーが発生しました。\n原因: {0}。</entry>
    <entry key="WriteToWorkerError">ワーカー {0} への送信中に書き込みエラーが発生しました。</entry>
    <entry key="WriteToWorkerErrorWithCause">ワーカー {0} への送信中に書き込みエラーが発生しました。\n原因: {1}。</entry>
    <entry key="RemoteInvocationError" context="error">Unable to invoke method {0} on remote service {1}.</entry>
    <entry key="RemoteInvocationErrorWithCause" context="error">Unable to invoke method {0} on remote service {1}.\nThis was caused by: {2}.</entry>
    <entry key="UnknownRemoteExecutionFailure" context="error">Unknown remote execution failure:\n{0}.</entry>
  </message>
</rsccat>
