<!DOCTYPE HTML><html xmlns="http://www.w3.org/1999/xhtml"><body><strong>Explanation</strong><br/><p>Using <code>lasterror</code> and <code>lasterr</code> for
                    obtaining information about an error (such as the message ID and the stack
                    trace) is not recommended because errors in other activities (such as callbacks)
                    can result in these functions returning unexpected values.</p><p>If you specify a variable with a <code>catch</code> block and an error
                    occurs in the <code>try</code> block, MATLAB enters the
                        <code>catch</code> block and assigns the
                        <code>MException</code> object to the catch variable. The
                        <code>MException</code> object contains the error message, the
                    message ID, and the stack trace. To pass this information to a calling function,
                    either return the <code>MException</code> object as an output of your
                    function, or call its <code>rethrow</code> method to rethrow the error.
                    There is no need to save and restore <code>lasterr</code> around such a
                        <code>try/catch</code> block.</p><br/><strong>Suggested Action</strong><br/><p>Specify a variable with a <code><a href="matlab:doc catch" target="_blank">catch</a></code> block, as described in <a href="matlab:helpview([docroot '/techdoc/matlab_prog/matlab_prog.map'],'prog_try_catch_stmnt')" target="_blank">”The try-catch Statement”</a>.</p></body></html>